name: bem_estar_funcionarios
description: "App de bem-estar para funcionários públicos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  http: ^1.1.0          # Para requisições REST
  googleapis_auth: ^1.3.0 # Autenticação com Google
  provider: ^6.1.1      # Gerenciamento de estado
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/positive-leaf-459218-i6-fcae8cbf1016.json # Arquivo de chave
    - assets/government_logo.png # Logo do governo