name: bem_estar_funcionarios
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter  # Mantenha essa linha padrão
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.1.0
  dialogflow_grpc: ^0.2.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  # Adicione os assets aqui
    - assets/positive-leaf-459218-i6-fcae8cbf1016.json